### PR TITLE
Re-add additional files

### PR DESCRIPTION
**Pull request by filliph**
This re-adds the additional files scanning which must have been removed mistakenly, as these files are critical to the integrity of an addon repository.

### CODE REVIEW

**Comment by ticktackk** [comment]
I removed additional files scanning because all files during development stage are supposed to be under `_files` directory but I can now see how copying additional files can be useful for add-ons which has it's own callback file in the root of XF2 installation such as [DB Tech] Donate.

But this would mean even javascript files would be copied into `_repo` directory.

**Comment by filliph** [comment]
> But this would mean even javascript files would be copied into _repo directory.

Why in the world would anyone not want to commit their JS files? 🤨

**Comment by filliph** [comment]
If this is a contentious feature then I would suggest adding a per-addon option to decide whether to include additional_files or not.

**Comment by ticktackk** [comment]
When running the commit command devtools will attempt to copy the contents of `_files\js` directory to `_repo/upload/js` which seems pointless when we can use `<xf:js addon="TickTackk/SenjougaharaBestWaifu" src="ticktackk/senjougahara_best_waifu/some_file_name.js" min="1" />`

**Comment by filliph** [comment]
Not everyone uses XF2's `build-release` command to build their releases :)

**Comment by filliph** [comment]
EDIT: Nevermind, I see that the additional_files will read from the `_files` directory by default and fall back if not found. My bad.

**Comment by filliph** [comment]
Not rightly sure how a conflict happened since I thought I was being careful but in either case, the changes should make sure this works for every case (both custom release builders and XF2 release builder) when copying files into the _repo directory :)

**Pull request merged**
